### ISSUE TITLE
withCredentials() on Cross-Origin-Calls

### ISSUE THREAD

**Issue by nob13** [RusticiSoftware/TinCanJS#104]
Hello,

we are working on a learning platform based upon TinCan. Most course suppliers are using the Rustici-Tincan-Library and we like it. The course storage is on a different domain than the LRS-Endpoint. However we would like our users to be authenticated at the LRS in order to check if users are allowed to send this specific Tincan-Statement.

In our case Authentication is done via Cookies. Now we have the problem, that the TinCan-Calls do not contain any cookies at all. As they are Cross-Origin-Calls (CORS-Headers are all set) they need to have 'withCredentials' set inside the XMLHttpRequest object, otherwise cookies won't be send. Interestingly TinCanJS looks for this specific attribute and sets `env.hasCORS` to `true` but this gets not evaluated...

Is it planned to call withCredentials() in the future?

**Comment by brianjmiller** [comment]
There isn't a specific plan in place to include it in the future, though pull requests tend to have the effect of speeding up any plan :-). I can honestly say I'd not looked into `withCredentials` enough to know what it did beyond indicating CORS capability in a client. I'm not opposed to adding the capability to set it so that cookies are sent though it would be a fairly unorthodox usage of Tin Can at the moment. I wouldn't want to just set it by default to on as that would be a pretty big change in the request dynamic. 

Presumably in this case there is no "Authorization" header sent, and in general I think this becomes a new "Auth Type" for the library so would need to have a config setting for the LRS object to activate it. It would also be an issue in the Node environment because we don't have a cookie jar working automatically for us, though that could be set aside and just prevent constructing an LRS object in that environment, or hook into whatever the request module provides for cookie handling.

**Comment by nob13** [comment]
Thanks for your response. I am also not sure if it would be making sense in activating this flag by default inside the TinCan-Library because it may imply other problems or raise security concerns. 

Anyway, we circumvented the problem now with putting the LRS and the Course Storage behind the same reverse proxy thus making them visible by being served from the same domain and disabling CORS entirely. 

I just wanted to make sure if there isn't not another "hidden" configuration option we could use ;)
