### ISSUE TITLE
default to async?

### ISSUE THREAD

**Issue by garemoko** [RusticiSoftware/TinCanJS#108]
TinCanJS supports synchronous calls and the basic usage example in the documentation is synchronous. 

Synchronous XMLHttpRequests are now deprecated in Chrome and Firefox. 

We should update the documentation example to only show asynchronous examples and perhaps consider deprecating synchronous calls in TinCanJS in favour of making all calls asynchronous by default. This could be a breaking change for some implementers, but they will break in some future version of Chrome and Firefox anyway.

**Comment by brianjmiller** [comment]
I've been tracking a bit of an internal roadmap for TinCanJS and this was very much on it. Removing synchronous capability I imagine would be a huge backwards compatibility issue which is why I've not gone too far down the path of doing it, but yes I expect we'll get there at some point. I'm going to open a "roadmap" issue tracker in case anyone wants to comment. There is an example asynchronous call on the home page currently: http://rusticisoftware.github.io/TinCanJS/ though I can't say whether people understand that all of the other (than query) calls have the same capability. They would if they read the API doc, that's a big if :-).

**Comment by brianjmiller** [comment]
@garemoko see #110.

**Comment by garemoko** [comment]
Should I now close this issue?

**Comment by brianjmiller** [comment]
Up to you.
