### ISSUE TITLE
instantiating using `url` property on object bombing on file protocol

### ISSUE THREAD

**Issue by bbudd** [RusticiSoftware/TinCanJS#124]
if I do 

````javascript 
tinCan = new TinCan({
  url: window.location.toString()
});
````

where `window.location.toString()` starts with `file:`, the instantiation fails. 

Specifically [here](https://github.com/RusticiSoftware/TinCanJS/blob/90832a7a2494b193ea5a7e2c3b19675d42330e6c/src/Utils.js#L306) - when it starts with `file:` then `match`becomes null, and `match[x]` can no longer even be `undefined`, it throws an error.

**Comment by garemoko** [comment]
I except that you'll hit a bunch of other problems using content hosted at file:// Any reason not to use localhost?

**Comment by brianjmiller** [comment]
@bbudd @garemoko is correct, some browser implementations of CORS prevent any requests being made cross scheme, for the ones that do work cross scheme they are a limited set and almost exclusively to 'https', and if you can find one that works from a `file://` scheme then you'd further have to expect the LRS to have specific headers allowing it which the spec doesn't require and I think you are unlikely to find. So we've hobbled `parseURL` on purpose. AFAIK the only other place we use it internally is for `more` URL handling, but since an LRS must be talking over HTTP we can be safe assuming `http` or `https` as the scheme for an endpoint.
