### ISSUE TITLE
Unity with TinCan API Version Question

### ISSUE THREAD

**Issue by bstevens762** [RusticiSoftware/TinCanJS#145]
I have been trying to implement TinCan into Unity 5.6.1 so that I could send messages to scorm cloud/ another LRS with it. From my research it seems unity only supports up to .NET 3.5, but I am currently getting errors that read:
'retarget your application to a framework version which contains "System.Web, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"'

I interpret this to mean I am not running the correct version of Tin Can or .NET framework, is this the case?

**Comment by SpaceCaseChris** [comment]
Hey bstevens762, I ran into this a while back for a similar version of
Unity as well. I ended up having to pull the source for the
https://github.com/RusticiSoftware/TinCan.NET, and retarget .NET with it
open as its own project. I don't remember the exact steps, but will dig up
my notes when I am back at home. Make sure you are using the full version
of .NET rather than .NET subset (which is the default option) as well.

It's worth noting that Unity 2017.1 now supports up to .NET 4.6, which I
think should cover everything in TinCan.NET (which only requires 3.5), but
if migrating isn't an option (it wasn't for us at the time), I was able to
get basic statements up and running no problem with the approach above.

**Comment by bstevens762** [comment]
Thanks for the answer SpaceCaseChris, I will be trying this this week and I'll update the question if I resolve my issues.

**Comment by SpaceCaseChris** [comment]
Hey @bstevens762 apologies for not getting back sooner - life got busy with the arrival of our second little one. Unfortunately my notes and work on this were collected when I left my previous position. Hoping you were able to get something worked out? If not I can try to replicate at home while off work.

The particular quirk I recall with Unity 5.x was that you only had a subset of .NET being brought in in the first place, and even when switching to to full .NET import it was mostly 2 with some elements of 3.5.  This may all be hearsay and/or misinformation - that’s just what sticks out in my memory, but it has been a while.

Looking forward to your results!

**Comment by bstevens762** [comment]
Chris,

Congratulations on your good news and thanks again for your input. I've
found it very difficult to dig up information on this in general but you've
been helpful especially as I probably wouldn't have realized about Unity's
.NET limitations without you. That project got pushed due to other projects
at my work but I should be getting back to it this week, hoping for
success. Ill let you know if I find a concrete solution.
